#!/usr/bin/perl

use lib '../cgi-bin';
use lib '../util';

use Launchh;
use strict;
use Data::Dumper;
    
#$Launchh::HFILE = "empty-ll2.html";

my $username = $Launchh::_query->param('uname');
my $firstname = $Launchh::_query->param('firstname');
my $tosend = $Launchh::_query->param('tosend') || 0; 
my $message = $Launchh::_query->param('message'); 
#my $message = $Launchh::_query->param('message') ; 

my $dir_str = "../";

$Launchh::u = $Launchh::_query->param('uname');

&Launchh::select_accounts("WHERE account_username='$Launchh::u'");
&Launchh::next_account();

my $toname = $Launchh::account->{'account_name_first'}. " ". $Launchh::account->{'account_name_last'}; 

print $Launchh::_query->header();
print html_send_message();
&Launchh::clean_exit();

sub html_send_message
{
		
	my $update_str = << "EOM";

<div class="popup" id="confirmation-top">
		<div class="popup-head" id="confirmation">
		<h2>Want to make an introduction to someone in your network?</h2>
	</div><!-- /.popup-head -->

	<div class="popup-body">
		<p>Your friend will receive an email sharing this entrepreneur’s profile page</p>

		<div class="form form-refer">
			<form onsubmit="return sendEmail();">
				<div class="form-body">
					<div class="form-row">
                          <div class="form-controls">
					     		<input type="text" name="sendername" id="sendername" class="field" placeholder="Your Name" />
					     		<input type="text" name="refer-email" id="refer-email" class="field" placeholder="Your Friend's Email" />
							    <input type="hidden" name="tosend" id="tosend" value="1"/>
							    <input type="hidden" name="username" id="username" value="$username"/>
							    <input type="hidden" name="firstname" id="firstname" value="$firstname"/>
						</div><!-- /.form-controls -->
					</div><!-- /.form-row -->
				</div><!-- /.form-body -->

				<div class="form-actions">
					<input type="submit" value="Refer" class="btn btn-medium" />
				</div><!-- /.form-actions -->
			</form>
		</div><!-- /.form form-refer -->
	</div><!-- /.popup-body -->
</div><!-- /.popup -->

<script>
            function sendEmail() {
                // 1. Create XHR instance - Start
                
                var xhr;
                if (window.XMLHttpRequest) {
                    xhr = new XMLHttpRequest();
                }
                
                else if (window.ActiveXObject) {
                    xhr = new ActiveXObject("Msxml2.XMLHTTP");
                }
                else {
                    throw new Error("Ajax is not supported by this browser");
                }
                
                // 1. Create XHR instance - End
                
                // 2. Define what to do when XHR feed you the response from the server - Start
                
                xhr.onreadystatechange = function () {
                if (xhr.readyState === 4) {
                        if (xhr.status == 200 && xhr.status < 300) {
                            // document.getElementById('loadix').innerHTML = xhr.responseText;
                            if(xhr.responseText == "success"){
                                parent.\$('#colorbox').height("150px");
                                //parent.\$('#colorbox').css('top', '35%');
                                \$('#confirmation-top').removeClass("popup");
                                \$('#confirmation-top').html("<div class='popup-confirm' align=center style='{font-style:italic, font-size: 12px, color: #3A3}'><br><br><br>Referral sent successfully</div>");
                                \$('#tosend').val(0);
                            }
                            else {
                                \$('#confirmation').html("<h4>Email sending failed. Please contact administrator</h4>");
                            }
                        }
                    }
                }
                // 2. Define what to do when XHR feed you the response from the server - Start

                
                var torefer = document.getElementById("refer-email").value;
                var tosend = document.getElementById("tosend").value;
                var username = document.getElementById("username").value;
                var sendername = document.getElementById("sendername").value;
                var firstname = document.getElementById("firstname").value;
                
                if(myTrim(sendername) == '' || myTrim(torefer) == ''){
                    \$('#confirmation').html("<h4>Please enter a valid name and email address to send your referral</h4>");
                    return false;
                }                
                var post_str = "torefer=" + torefer+"&username="+username+"&firstname="+firstname+"&sendername="+sendername;

                //alert(post_str);
                // 3. Specify your action, location and Send to the server - Start 
                if(tosend == 1){
                    xhr.open('POST', '$dir_str'+'ajax/launchmailer');
                    xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                    xhr.send(post_str);
                }
                // 3. Specify your action, location and Send to the server - End

                return false;
          }

                
     function myTrim(x) {
        return x.replace(/^\\s+|\\s+\$/gm,'');
    } 
</script>

EOM
		
return $update_str;
}



sub trim
{
    my $str = shift;
    
    $str =~ s/^\s+//;
    $str =~ s/\s+$//;
    
    return $str;
}