#!/usr/bin/perl

##!D:/TOWORK/bin/xampp/perl/bin/perl.exe

use lib 'cgi-bin';
use lib 'util';
use Launchh;
use strict;
use Data::Dumper;
use POSIX qw(floor);
use POSIX qw(ceil);
    
#$Launchh::HFILE = "empty-ll2.html";

my $username  = $Launchh::_query->param("u") ;

print $Launchh::_query->header();
print_header(); # &Launchh::html_header($Launchh::HFILE,$Launchh::HSTR);
print html_discover();
print_footer();
#print &Launchh::html_footer($Launchh::HFILE,$Launchh::HSTR);

&Launchh::clean_exit();


sub html_discover
{
#=begin
	my $update_str = "no-data";
	my $account_filtering_str = " AND account_username = '$username' ";
	#$account_filtering_str = " AND account_id = '29' ";
	my $account_status = 80001;
	my $project_status = 80002;
    my $incomplete_status = 79999; 
    my $campaign_wpi_status = 80005;
    

    my $page_url = 'http';
    if ($ENV{HTTPS} && lc $ENV{HTTPS} ne "off") {
    $page_url .= "s";
    }
    $page_url .= "://";
    $page_url .= $ENV{SERVER_NAME};
        
    my $idea_profile_search_sql = "";
    
    #$idea_profile_search_sql = "WHERE account_username IS NOT NULL AND account_status IN($project_status,$campaign_wpi_status) $account_filtering_str ";
    $idea_profile_search_sql = "WHERE account_username IS NOT NULL  $account_filtering_str ";
    
	&Launchh::select_accounts($idea_profile_search_sql);
	while(&Launchh::next_account())
    {
		my @detailArr;
        
        $update_str = "" if($update_str eq 'no-data');

		&Launchh::select_details("WHERE detail_type=2 AND detail_status=1 ORDER BY CAST(detail_note AS DECIMAL(5,1))");
		while(&Launchh::next_detail())
		{
		   &Launchh::select_question($Launchh::detail->{'detail_desc'});
		   
		   #select user's previous answer, if any
		   &Launchh::select_account_details("WHERE account_id=$Launchh::account->{'account_id'} AND detail_id=$Launchh::detail->{'detail_id'} AND account_detail_status=1 ORDER BY account_detail_id desc LIMIT 1");
		   &Launchh::next_account_detail();
		   
		   my $detail_value = $Launchh::account_detail->{'account_detail_desc'};
		   my $detail_id = $Launchh::detail->{'detail_id'};
		   
		   $detailArr[$detail_id] = $detail_value;
		}

		my $uid = $Launchh::account->{'account_id'};
		my $first_name = $Launchh::account->{'account_name_first'};
		my $last_name = $Launchh::account->{'account_name_last'}; 
		my $full_name = $first_name." ".$last_name;
		my $headline = $Launchh::account->{'account_desc'};
		my $username = $Launchh::account->{'account_username'}; 
		my $location = $Launchh::account->{'account_phone'}; 
        my $fund_limit = 0 ;
		
        #$full_name = " " if(trim($full_name) eq '');
        $location = "&nbsp;" if(trim($location) eq '');
        $headline = "&nbsp;" if(trim($headline) eq '');
        
        #my $len1 = length($headline);
        
		&Launchh::select_element_details("WHERE account_id = $Launchh::account->{'account_id'} AND element_detail_status = '1'" );
		while(&Launchh::next_element_detail()){
			&Launchh::select_elements("WHERE element_status=1 AND element.element_id = $Launchh::element_detail->{'element_id'}");
			&Launchh::next_element();
			if($Launchh::element->{'element_id'} eq '') {
				next;
			}
	        $fund_limit += $Launchh::element->{'element_amount'};
		}
		
		my $current_fund = 0 ;
		#$current_fund = ceil(&Launchh::total_funded("WHERE account_id = $Launchh::account->{'account_id'}" ));       
        $current_fund = ceil(&Launchh::total_funded("WHERE funding_details.account_id = $Launchh::account->{'account_id'}" ));
        
        
        my $fund_percentage = 0;
		$fund_percentage = ceil ($current_fund / $fund_limit  * 100)  if($fund_limit > 0);

		my $summary = $detailArr[27];
		my $profile_photo= $detailArr[25];
		my $college = $detailArr[16];
		my $experience= $detailArr[43];
		my $seeking= $detailArr[24];
		my $skill1= $detailArr[17];
		my $skill2= $detailArr[22];
		my $skill3= $detailArr[23];
		my $speciality= $detailArr[12];
        my $experience= $detailArr[43];
        my $facebook= $detailArr[46];
        my $twitter= $detailArr[47];
        
        my $summary_length_limit = 200;
        my $headline_length_limit  = 80;
        

        my $twitter_name = '';
        if( $twitter =~/.*twitter.com\/(.*?$)/){
            $twitter_name = $1;
        }
        #$twitter_name = $twitter if($twitter_name eq '');
         if($twitter_name eq '' && $facebook =~/.*twitter.com\/(.*?$)/){
              $twitter_name = $1;
         }
            
		if($profile_photo eq ''){
			#$profile_photo = "images/launch-leader-default.jpg";
			$profile_photo = "images/launchleader-human-avatar-discover.png";
		}
		else{
			$profile_photo = "uploads/$uid/images/$profile_photo";
		}
		
        my $trail = '';
        if(length($summary) > $summary_length_limit)
        {
            #$trail = '...';
        }        
        
        my $trail_headline = '';
        if(length($headline) > $headline_length_limit)
        {
            #$trail_headline = '...';
        }
        $headline = string_shorten($headline, $headline_length_limit, 40);

		#$summary = summary_short($summary, 185);
        
        
		my $fb_app_id = $Launchh::FB_APP_ID;
		my $page_url_to_share = $page_url."/profile/$username";
		
        $update_str .= << "EOM";
                                    <li class="update">
								<div class="update-image">
									<a href="profile/$username">
                                                    <div class="discover-image-container" style='background-image: url($profile_photo);'></div>
                                    		</a>
								</div><!-- /.update-image -->
						
								<div class="update-content">
									<h3>
										<a href="profile/$username">$full_name</a>
									</h3>									
                                    
									<h4>$headline $trail_headline</h4> 
									
									<span>
										<i class="ico ico-location"></i>$location
									</span>
						
                                              <section>
                                                <p>
                                                        $summary $trail
                                                  </p>                                                  
                                            <div class="fadeout"></div>
                                            </section>
                                            <div class="update-share">
										<ul>
										<!--
											<li>
												43
												<i class="ico ico-up"></i>
											</li>
											-->
											<li>
													<a href="javascript:popupwindow(\'https://www.facebook.com/sharer/sharer.php?app_id=$fb_app_id&sdk=joey&u=$page_url_to_share&display=popup&ref=plugin\',\'title\',\'650\',\'350\')" class="btn btn-fb-share"></a> 
											</li>
											
											<li>
													<a href="javascript:popupwindow(\'https://twitter.com/intent/tweet?text=Join me supporting %23$twitter_name by $first_name $last_name&url=$page_url_to_share&via=sivicorp\',\'title\',\'650\',\'350\')" class="btn btn-tw-tweet"></a>
											</li>
											<li>
                                                                <a href="../social/get_short_url?tsu=$username"  class="btn btn-link-share modal-trigger"></a>
                                            </li>                                            
										</ul>
                                        </div><!-- /.update-share -->
EOM
                $update_str .= << "EOM";
									<div class="update-funding">
										<div class="funding-progress">
											<span style="width: $fund_percentage%;"></span>
										</div><!-- /.funding-progress -->
										
										<span class="funding-start">$fund_percentage% Raised</span>
										
										<span class="funding-end">\$$fund_limit</span>
									</div><!-- /.update-funding -->
EOM
                                    
                $update_str .= << "EOM";                                    
                                        </div><!-- /.update-content -->
                                        <!--
								<div class="update-actions">
									<a href="profile/$username" class="btn btn-medium">View Profile</a>
								</div><!-- /.update-actions -->
							</li><!-- /.update -->
                            
    <script>
            function popupwindow(url, title, w, h) {
              url = url.replace("#","%23") 	    
              var left = (screen.width/2)-(w/2);
              var top = (screen.height/2)-(h/2);
              return window.open(url, title, 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width='+w+', height='+h+', top='+top+', left='+left);
            }         
        </script>                            
                            
EOM

	}

return $update_str;
}


sub print_header
{

   my $header .= << "EOM";   
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head>
 	<title>Launch Leader v4</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
	
    <link rel="shortcut icon" href="../css/images/favicon.ico" />
	<link rel="stylesheet" href="../css/fonts.css" type="text/css" media="all" />
	<link rel="stylesheet" href="../css/jquery.fs.selecter.css" type="text/css" media="all" />
	<link rel="stylesheet" href="../css/style-embed.css" type="text/css" media="all" />
     
     <script type='text/javascript' src='//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'></script>   
     <script type='text/javascript' src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
     <script type="text/javascript" src="../js/jquery-1.11.0.min.js"></script>
	
	<script type="text/javascript" src="../js/functions.js"></script>
	
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <meta property="og:title" content="TITLE_FOR_SOCIAL_SITE"/>
</head>

<body style=" background: #fff;">
	<div class="main">
    	<div class="section section-home-updates ">
					<ol class="updates" id="no-slider-idea">
EOM
   print $header;
}

sub print_footer
{
   my $footer .= << "EOM";   
   				</ol><!-- /.updates -->
		</div><!-- /.section section-home-updates -->
   					</ol><!-- /.updates -->
				</div><!-- /.section-body -->
       </div><!-- /.main -->
</body>
</html>

EOM
   print $footer;
}

sub string_shorten 
{
	my $text = shift;
	my $limit = shift;
	my $linebreak = shift;
    
    my $tmp = substr($text,0,$limit);
	#$tmp =~ s/\s+\w*$//g;	
    $tmp =~ s/^\s+//;
    $tmp =~ s/\s+$//;
    
	$text = $tmp;
    
    my $textlength = length($text);
    
    if( $textlength < ($limit - 10))
    {
        my $inx = 0; 
        
        $inx = floor ($textlength / $linebreak) * $linebreak;
        while($inx < $limit) {
            $text .= "<br>";
            $inx = $inx + $linebreak;
        }
    }
	
	return $text;
}

sub trim
{
    my $str = shift;
    
    $str =~ s/^\s+//;
    $str =~ s/\s+$//;
    
    return $str;
}