#!/usr/bin/perl

#use lib '../../siviacademy.com/cgi-bin';
use lib 'cgi-bin';
use lib 'util';
use Launchh;
use CGI::Session;

my $session = new CGI::Session("driver:File", undef, {Directory=>"/tmp"});
my $cgi = new CGI;
my $cookie = $cgi->cookie( "CGISESSID", $session->id );
$session->expire("+15m");

$Launchh::uid = $session->param("uid") if($Launchh::uid  eq '');

my $pmode  = $session->param("pmode") if(defined $session->param("pmode"));
$pmode = $Launchh::_query->param('pmode') if($pmode eq '');

if($pmode ne  ''  && $pmode ne  'launchleader') {
	$Launchh::HFILE = "template/empty-$pmode.html";
}
else{
	$Launchh::HFILE = "empty-ll2.html";
}

my $og_title = "";
print $Launchh::_query->header();
print_header(); # &Launchh::html_header($Launchh::HFILE,$Launchh::HSTR);
print html_privacy();
print_footer();

&Launchh::clean_exit();


sub html_privacy
{
    my $str .=<<EOM;
	<div class="section section-faq">
			<div class="shell">
				<div class="section-faq-inner">
					<div class="section-head">
                                    <h2>Privacy Policy</h2>

                                    <p>Sivi Corporation (“<b>LaunchLeader</b>”)</p>
					</div><!-- /.section-head -->
                    
					<div class="section-body">
						<section class="faq-content">
                        <p>Effective December 5, 2014</p>

                        <p>&nbsp;</p>

                        <p>Sivi Corporation (&quot;<b>LaunchLeader</b>,&quot;
                        &quot;<b>we</b>,&quot; or &quot;<b>us</b>&quot;) knows that you care how
                        Personal Information about you is collected, used, shared and stored. &quot;<b>Personal
                        Information</b>&quot; means information which personally identifies you or
                        another.</p>
                        
                        <p>&nbsp;</p>



                        <p>This Privacy Policy explains
                        what Personal Information will be collected by LaunchLeader when you use our
                        Website:<b>https://www.launchleader.com/</b> and related services (the &quot;<b>Service</b>&quot;),
                        how Personal Information will be used, and how you can control the collection,
                        correction and/or deletion of Personal Information.</p>
                        
                        <p>&nbsp;</p>


                        <p>This Privacy Policy should be
                        read along with our Terms of Use posted at: <a
                        href="/terms" target="_blank"><b>https://www.launchleader.com/terms</b></a> (&quot;<b>Agreement</b>&quot;),
                        and all other operating rules, policies and procedures and additional terms and
                        conditions published on our Website (all of which are incorporated by
                        reference) which governs your use of our Website and Service. Capitalized
                        terms, if not defined in this Privacy Policy, are defined in the Agreement.</p>

                        <p>&nbsp;</p>

                        <p><b>E.U. Safe Harbor</b></p>

                        <p>&nbsp;</p>

                        <p>LaunchLeader complies with the
                        U.S. - E.U. Safe Harbor framework and the U.S. - Swiss Safe Harbor framework as
                        set forth by the U.S. Department of Commerce regarding the collection, use, and
                        retention of personal data from European Union member countries and Switzerland
                        LaunchLeader has certified that it adheres to the Safe Harbor Privacy
                        Principles of notice, choice, onward transfer, security, data integrity,
                        access, and enforcement. To learn more about the Safe Harbor program, and to
                        view LaunchLeader's certification, please visit <a
                        href="http://www.export.gov/safeharbor/" target="_blank"><b><span style='color:windowtext;
                        text-decoration:none'>http://www.export.gov/safeharbor/</span></b></a>.</p>

                        <p>&nbsp;</p>


                        <p><b>Mobile Privacy</b></p>

                        <p>&nbsp;</p>

                        <p>We may offer you the ability to
                        connect with our Website, or use our applications, services, and tools using a
                        mobile device, either through a mobile application or via a mobile optimized
                        website. The provisions of this Privacy Policy apply to all such mobile access
                        and use of mobile devices. This Privacy Policy will be referenced by all such
                        mobile applications or mobile optimized websites.</p>


                        <p>&nbsp;</p>

                        <p><b>Personal Information We
                        Collect or You May Provide</b></p>


                        <p>&nbsp;</p>

                        <p>You provide us Personal
                        Information when you register to be a Member:</p>



                        <p class=MsoListParagraphCxSpFirst style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your name</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your email address</p>

                        <p class=MsoListParagraphCxSpLast style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>You may provide your location</p>


                        <p>&nbsp;</p>

                        <p>If you create a Campaign, or
                        join as a Campaign team member, you will provide us with the following Personal
                        Information in addition to the Personal Information you provide when you
                        register to be a Member:</p>



                        <p class=MsoListParagraphCxSpFirst style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your legal person or business name</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your legal physical address</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your Tax ID (if you are a business)</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your telephone number</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your date of birth</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your Stripe account information (if accepting payments via Stripe)</p>

                        <p class=MsoListParagraphCxSpLast style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your bank account information.</p>


                        <p>&nbsp;</p>

                        <p>As a Contributor, you may
                        provide:</p>



                        <p class=MsoListParagraphCxSpFirst style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your name</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your email address</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Ship-to information</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your billing name and address</p>

                        <p class=MsoListParagraphCxSpLast style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your Stripe e-mail address</p>


                        <p>&nbsp;</p>

                        <p>You may be asked further
                        information in order to help validate your identity:</p>



                        <p class=MsoListParagraphCxSpFirst style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your gender</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Your driver's license information, government issued
                        identification number</p>

                        <p class=MsoListParagraphCxSpLast style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Other personally identifiable information as we need for
                        verification</p>


                        <p>&nbsp;</p>

                        <p>We may obtain address
                        information about you from third party sources, such as LexisNexis, for fraud
                        prevention or for legal compliance.</p>


                        <p>&nbsp;</p>

                        <p>We may also collect Personal
                        Information from you as a result of your email communications with us or your
                        Posts, which we may retain along with our responses.</p>


                        <p>&nbsp;</p>

                        <p>As a Campaign Owner, you can
                        invite others who are helping you with your campaign to join your campaign
                        team. We will ask you for this person's email address and send him or her an
                        email invite to join your team. LaunchLeader collects this email address for
                        the purpose of sending this invite. This person may contact us at <b>privacy\@launchleader.com</b>
                        to request that we remove this information.</p>
                        <p>&nbsp;</p>



                        <p>Any Personal Information you
                        Post as Member Content is available to the public without any expectation of
                        privacy or confidentiality. Copies may remain viewable in cached and archived
                        pages or if other Users have copied or stored your Member Content even if you
                        remove the Member Content. To request removal of your personal information from
                        these areas of the site, contact us using the information below. In some cases,
                        we may not be able to remove your personal information, in which case we will
                        let you know if we are unable to do so and why. The profile you create on our
                        site will be publically visible. </p>

                        <p>&nbsp;</p>


                        <p>We display personal testimonials
                        of satisfied users on our site in addition to other endorsements. With your consent
                        we may post your testimonial along with your name. If you wish to update or
                        delete your testimonial, you can contact us using the information below.</p>

                        <p>&nbsp;</p>


                        <p>When you use our mobile site, we
                        may receive information about your location and your mobile device, including a
                        unique identifier for your device. We may use this information to provide you
                        with location based services, search results, and other personalized content.
                        Most mobile devices allow you to control or disable location services in the
                        device's setting's menu. If you have questions about how to disable your
                        device's location services, we recommend you contact your mobile service
                        carrier or the manufacturer of your particular device.</p>

                        <p>&nbsp;</p>

                        <p><b>How We Use Your Personal
                        Information</b></p>

                        <p>&nbsp;</p>


                        <p>We use your Personal Information
                        to operate, maintain, and provide to you the Service and conduct our business.
                        For example (and not limited) to:</p>


                        <p>&nbsp;</p>

                        <p class=MsoListParagraphCxSpFirst style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Register as a Member and to identify you when you sign-in to your
                        account</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Administer your account or funds</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Respond to your inquiries, customer service requests, complaints
                        or your job application</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Verify activity as we deem necessary</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Send you a newsletter or other promotional communications</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Conduct research and analyze data to improve our Service or
                        customize our communications with you</p>

                        <p class=MsoListParagraphCxSpLast style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>Communicate with you</p>

                        <p>&nbsp;</p>


                        <p><b>How We Share Your Personal
                        Information with Third Parties</b></p>


                        <p>&nbsp;</p>

                        <p>We will share your personal
                        information with third parties only in the ways that are described in this
                        privacy policy. We do not sell your Personal Information to third parties.</p>
                        <p>&nbsp;</p>

                        <p>We may share your Personal
                        information:</p>

                        <p class=MsoNormal style='margin-left:0in;text-indent:0in;text-autospace:none'><span
                        style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span>&nbsp;</p>

                        <p class=MsoListParagraphCxSpFirst style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>As required by law, such as to comply with reporting
                        requirements, a subpoena, or similar legal process.</p>

                        <p class=MsoListParagraphCxSpMiddle style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>In connection with an investigation of fraud, intellectual
                        property infringement, piracy, or other unlawful activity or as we believe
                        reasonably necessary to protect or enforce our rights, protect your safety or
                        the safety of others.</p>

                        <p class=MsoListParagraphCxSpLast style='text-indent:-.25in;text-autospace:
                        none'><span style='font-family:Symbol'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </span></span>With any other member, contributor, campaign owner or third party
                        with your prior consent to do so as described in this Policy.</p>

                        <p>&nbsp;</p>


                        <p>If you are a Contributor, we
                        share your name, email and shipping address with the Campaign Owner or Campaign
                        team member.</p>


                        <p>&nbsp;</p>

                        <p>If you are a Campaign Owner, we
                        may share your name, email address, and other contact information with any
                        Contributor who alleges that you have failed to comply with your Campaign
                        commitments.</p>

                        <p>&nbsp;</p>


                        <p>We may provide your personal
                        information to companies that provide services to help us with our business
                        activities such as processing your payments, accepting job applications and
                        offering customer service. These companies are authorized to use your personal
                        information only as necessary to provide these services to us and are obligated
                        to keep your information confidential. Some of our pages utilize framing
                        techniques to serve content from our service providers while preserving the
                        look and feel of our site, such as when you enter credit card information.
                        Please be aware that you are providing your personal information to these third
                        parties and not to <b>https://www.launchleader.com/</b>.</p>

                        <p>&nbsp;</p>


                        <p>If LaunchLeader is involved in a
                        merger, acquisition, or sale of all or a portion of its assets or bankruptcy,
                        you will be notified via email and/or a prominent notice on our Website of any
                        change in ownership or uses of your Personal Information, as well as any
                        choices you may have regarding your Personal Information.</p>

                        <p>&nbsp;</p>


                        <p><b>How We Store and Protect Your
                        Personal Information</b></p>

                        <p>&nbsp;</p>


                        <p>We may store Personal
                        Information in locations outside our direct control (for instance, on servers
                        or databases co-located with hosting providers).</p>


                        <p>&nbsp;</p>

                        <p>We use Security Sockets Layer
                        (SSL) encryption technology to encrypt sensitive personal information (such as
                        your email or password) before it travels over the internet. Credit card
                        numbers are never stored on our database or servers.</p>


                        <p>&nbsp;</p>

                        <p>The security of your personal
                        information is important to us. We follow generally accepted standards to
                        protect the personal information submitted to us, both during transmission and
                        once we receive it. However, no method of transmission over the Internet, or
                        method of electronic storage, is 100% secure. Therefore, we cannot guarantee
                        its absolute security. If you have any questions about security on our Web
                        site, you can contact us at <b>privacy\@launchleader.com</b>.</p>

                        <p>&nbsp;</p>


                        <p><b>Compromise of Personal
                        Information</b></p>

                        <p>&nbsp;</p>


                        <p>We will promptly notify those
                        persons whose Personal Information is compromised. Notwithstanding, LaunchLeader
                        does not accept liability for any unintentional disclosure or a disclosure that
                        occurs due to a security breach of our systems or facilities.</p>

                        <p>&nbsp;</p>


                        <p><b>User Access and Choice</b></p>

                        <p>&nbsp;</p>

                        <p>You may, of course, decline to
                        submit Personal Information to us; in which case, you may not be able to become
                        a Member or use certain Services.</p>



                        <p>If your Personal Information
                        changes, you may correct, update, amend, remove, or ask to have it removed by
                        making the change on your user account &quot;<b>Settings</b>&quot; page, by
                        contacting the email address listed below. If you no longer desire our service,
                        you may deactivate/delete your account entirely from the account &quot;<b>Settings</b>&quot;
                        page, or contact us directly. We will respond to your request within 30 days.</p>



                        <p>We will retain your Personal
                        Information for as long as your account is active or as needed to provide you
                        services. We will retain and use your Personal Information as necessary to
                        comply with our legal obligations, resolve disputes, and enforce our
                        agreements.</p>
                        <p>&nbsp;</p>



                        <p><b>Notification, Electronic
                        Communication and Opt-Out</b></p>

                        <p>&nbsp;</p>

                        <p>You consent to our using your
                        email address to send you Service-related notices, including any notices
                        required by law, in lieu of communication by postal mail. You may not opt out
                        of some Service-related communications. You can change the frequency of many
                        Service-related communications by changing the settings in the &quot;<b>Settings</b>&quot;
                        section.</p>


                        <p>&nbsp;</p>

                        <p>Upon registration, or on other
                        areas of the site, you may opt-in to receive periodic messages from us,
                        including changes to features of the Service, newsletters, promotions and
                        special offers. If you wish to subscribe to these emails, we will use your name
                        and email address to send them to you. Out of respect for your privacy, you may
                        choose to stop receiving our newsletter or marketing emails by following the
                        unsubscribe instructions included in these emails, accessing email preferences
                        manager on your account settings page or you can contact us at <b>privacy\@launchleader.com</b>.
                        Opting out may prevent you from receiving email messages regarding updates,
                        improvements, or offers.</p>


                        <p>&nbsp;</p>

                        <p><b>Children's Privacy</b></p>

                        <p>&nbsp;</p>

                        <p>Protecting the privacy of young
                        children is especially important. LaunchLeader does not knowingly collect or
                        solicit Personal Information from anyone under the age of 13 or knowingly allow
                        such persons to register. If you are between the ages of 13 and 17, please use
                        our Service with adult supervision. If you are under 13, please do not send any
                        Personal Information to us. If we learn that we have collected Personal
                        Information from a child under age 13, we will delete that information as
                        quickly as possible. If you believe that we might have any Personal Information
                        from or about a child under 13, please contact us at the contact information
                        below.</p>
                        <p>&nbsp;</p>



                        <p><b>Cookies, Analytics/Log Files
                        and Clear gifs</b></p>

                        <p>&nbsp;</p>

                        <p>This section explains
                        LaunchLeader’s use of cookies on LaunchLeader’s Website (the “<b>Cookie Policy</b>”).
                        We may amend this Cookie Policy at any time and all changes will be made on
                        this Web page. The changes will take effect once they have been posted on the
                        Website. Therefore, you should review this CookiePolicy on a regular basis. </p>



                        <p>If you do not agree with this CookiePolicy,
                        do not use or access (or continue to access) the Service.</p>



                        <p>LaunchLeader uses cookies and
                        other automated data collection tools when you use the Service. When you visit <b>www.launchleader.com</b>,
                        we may send one or more cookies – a small text file containing a string of
                        alphanumeric characters – to your computer.</p>



                        <p>LaunchLeader uses <b>session
                        cookies</b> and <b>persistent cookies</b>. A persistent cookie remains on your
                        hard drive after you close your browser. Persistent cookies may be used by your
                        browser on subsequent visits to the site. Persistent cookies can be removed by
                        following your web browser’s directions. A session cookie is temporary and
                        disappears after you close your browser.</p>

                        <p><b>&nbsp;</b></p>

                        <p><b>LaunchLeader uses the
                        following cookies:</b></p>

                        <p>&nbsp;</p>


                        <p><b>Strictly necessary or
                        essential cookies</b></p>

                        <p>Strictly necessary or essential
                        cookies are critical to the functionality and to navigate around the Website
                        and use its features. For example, we use these cookies to keep you logged in
                        to the Service and to remember relevant information about you when you return
                        to the Website.</p>

                        <p>&nbsp;</p>


                        <p><b>Performance cookies</b></p>

                        <p>Performance cookies collect
                        anonymous information about how you use the LaunchLeader Website. For example,
                        these cookies help us improve the usability of the Website by allowing
                        LaunchLeader to track how users move around the Website when they are using it.</p>


                        <p>&nbsp;</p>

                        <p><b>Functionality cookies</b></p>

                        <p>Functionality cookies also
                        collect anonymous information. They can also provide security in transactions.
                        For example, we use functional cookies to remember the choices you make and provide
                        enhanced features to improve your user experience. By way of example, these
                        cookies remember your user name and configurations of the Service that you
                        customize.</p>

                        <p>&nbsp;</p>


                        <p><b>Advertising and targeting
                        cookies</b></p>

                        <p>Advertising and targeting
                        cookies are used to deliver advertisements that are relevant to you and your
                        interests, and be used to chart the effectiveness of an ad campaign. They are
                        usually placed by third-party advertising networks with a website operator’s
                        permission, but can be placed by the operator themselves. They can remember
                        that you have visited a website, and this information can be shared with other
                        organizations, including other advertisers. Third-party advertisement networks
                        will show these cookie-triggered ads on sites across the Internet.</p>

                        <p>&nbsp;</p>


                        <p>Third-party advertisement
                        networks also use advertising and targeting cookies to allow LaunchLeader: (a)
                        to reach people who previously visited our Website and match you with the right
                        message and (b) to attract you back to our Website. Information about how you
                        can opt out of a third-party vendor's use of cookies can be found by visiting
                        the <a href="http://www.networkadvertising.org/choices/" target="_blank"><span
                        style='color:#3366FF'>Network Advertising Initiative opt-out page</span></a>.</p>


                        <p>&nbsp;</p>

                        <p>LaunchLeader does not provide
                        any personally identifiable information to these third-party ad servers or ad
                        networks without your consent. You should consult the respective privacy
                        policies of these third-party ad servers or ad networks. The LaunchLeader
                        privacy policy does not apply to, and we cannot control the activities of, such
                        advertisers.</p>
                        <p>&nbsp;</p>



                        <p><b>Log files, web beacons, clear
                        gifs</b></p>

                        <p>Log file information is
                        automatically reported by your browser each time you access a web page. When
                        you register with or view our Website, our servers automatically record certain
                        information that your web browser sends whenever you visit any website. These
                        server logs may include information such as your web request, Internet Protocol
                        (“IP”) address, browser type, referring / exit pages and URLs, number of
                        clicks, domain names, landing pages, pages viewed, and other such information.</p>

                        <p>&nbsp;</p>


                        <p>We use this information to
                        analyze trends, to administer the site, to track users’ movements around the
                        site and to gather demographic information about our user base as a whole.</p>

                        <p>&nbsp;</p>


                        <p>When you use the Service, we may
                        employ clear gifs (a.k.a. Web Beacons) which are used to track the online usage
                        patterns of our users anonymously. In addition, we may also use clear gifs in
                        HTML-based emails sent to our users to track which emails are opened by
                        recipients. The information is used to enable more accurate reporting, improve
                        the effectiveness of our marketing, and make LaunchLeader better for our Users.</p>

                        <p>&nbsp;</p>


                        <p><b>Browser Settings</b></p>

                        <p>&nbsp;</p>

                        <p>You may refuse to accept cookies
                        by activating the setting on your browser that allows you to block the setting
                        of all or some cookies. However, if you decide to block or restrict cookies on
                        your browser, you may be unable to access all or parts of the website. Please
                        be aware that restricting cookies may impact your user experience of our
                        website.</p>
                        <p>&nbsp;</p>

                        <p>If you continue to use the
                        LaunchLeader websites without changing your browser settings, you will have
                        consented to our cookie usage and agree that you understand our Cookie Policy.</p>

                        <p><b>&nbsp;</b></p>

                        <p><b>Links to Other Websites,
                        Blogs/Forums and Social Media Widgets</b></p>

                        <p>&nbsp;</p>

                        <p>Our Site includes links to other
                        Web sites whose privacy practices may differ from those of LaunchLeader. When
                        you use a link to go from our Website to another website, such as that of our
                        payments processors, the privacy statement for the other website governs. We
                        encourage you to carefully read and understand the privacy statement of any
                        Website you visit.</p>


                        <p>&nbsp;</p>

                        <p>Our Website offers a publicly
                        accessible blog. You should be aware that any information you provide in these
                        areas may be displayed publicly and read, collected, and used by others who
                        access them. To request removal of your personal information from our blog,
                        contact us at <b>privacy\@launchleader.com</b>. In some cases, we may not be
                        able to remove your personal information, in which case we will let you know if
                        we are unable to do so and why.</p>

                        <p>&nbsp;</p>


                        <p>Our Website includes Social
                        Media Features, such as the Facebook Like button and Widgets, such as the Share
                        this button. These Features may collect your IP address, which page you are
                        visiting on our Website, and may set a cookie to enable the Feature to function
                        properly. Social Media Features and Widgets are either hosted by a third party
                        or hosted directly on our Website. Your interactions with these Features are
                        governed by the privacy policy of the company providing it.</p>


                        <p>&nbsp;</p>

                        <p><b>English Language</b></p>

                        <p>&nbsp;</p>


                        <p>The English version of this
                        Privacy Policy governs. All disputes, claims and causes of action (and related
                        proceedings) will be communicated in English.</p>

                        <p>&nbsp;</p>


                        <p><b>Changes to Our Privacy Policy</b></p>

                        <p>&nbsp;</p>

                        <p>If we make a material change to
                        our privacy policies and procedures as to the collection, use or disclosure of
                        your Personal Information, we will post a notice of those changes on our
                        Website or notify you by email (sent to the email address specified in your
                        account) to keep you aware of what information we collect, how we use it and
                        under what circumstances we may disclose it, prior to the change becoming
                        effective. You are bound by changes to the Privacy Policy when you use the site
                        after those changes have been posted. We encourage you to periodically review
                        this page for the latest information on our privacy practices.</p>

                        <p>&nbsp;</p>


                        <p><b>Contact Us</b></p>

                        <p class=MsoNormal>&nbsp;</p>

                        <p class=MsoNormal>If you have any questions about this Privacy Policy, the
                        practices of this site, or your dealings with this Website, please contact us
                        at <b>privacy\@launchleader.com</b><a name="_GoBack"></a> or SIVI Corporation, 419
                        Lafayette St, 6th Floor, New York, NY 10003.</p>

						</section><!-- /.faq-content -->
					</div><!-- /.section-body -->
				</div><!-- /.section-faq-inner -->
			</div><!-- /.shell -->
		</div><!-- /.section .section-faq -->

EOM

return $str;

}


sub print_header
{
   my $header = &Launchh::html_header($Launchh::HFILE,$Launchh::HSTR);
#$user_header_str = " of ".$Launchh::account->{'account_name_first'} if($Launchh::account->{'account_name_first'} ne '');
   my $rand = rand(10000);

   $header =~ s/XXXTITLEXXX/USER PROFILE/is;
   if($Launchh::uid ne ''){
        $header =~ s/<li class="separator">\s*<a href=".*?login">Login<\/a>/<li class="separator"><a href="..\/logout?pmode=$pmode">Logout<\/a>/is  if($pmode ne '');        
        $header =~ s/<li class="separator">\s*<a href=".*?login">Login<\/a>/<li class="separator"><a href="..\/logout?$rand">Logout<\/a>/is ;        
        $header =~ s/DASHBOARDSTR/<li><a href="dashboard">My Dashboard<\/a><\/li>/is;   
        $header =~ s/SIGNUPSTR//is;
    }
    else{
        $header =~ s/DASHBOARDSTR//is;
        if($pmode eq ''){
            $header =~ s/SIGNUPSTR/<li class="signup"><a href=\"..\/signup\">Sign Up<\/a><\/li>/is;
        }
        else{
            $header =~ s/SIGNUPSTR/<li class="signup"><a href=\"\/signup?pmode=$pmode\">Sign Up<\/a><\/li>/is;
        }
    }
   
    if( $pmode ne '' && !defined $session->param("pmode") ){
        $header =~ s/faq">/faq\?pmode=$pmode">/is;   
        $header =~ s/login">/login\?pmode=$pmode">/is;   
        $header =~ s/discover">/discover\?pmode=$pmode">/is;   
        $header =~ s/privacy"/privacy\?pmode=$pmode"/is;   
        $header =~ s/terms"/terms\?pmode=$pmode"/is;   
        $header =~ s/SIGNUPSTR/<li class="signup"><a href=\"..\/signup?pmode=$pmode\">Sign Up<\/a><\/li>/is;                
    }   
   
   $header =~ s/TITLE_FOR_SOCIAL_SITE/$og_title/gs;
   
   my $headerold .= << "EOM";

		<aside class="sidebar">
			<ul class="widgets">
				<li class="widget widget-nav">
					<ul>
						<li>
							<a href="/dash?$Launchh::HSTR">
								<i class="icon-desktop"></i> Dashboard
							</a>
						</li>
		
						<li class="current">
							<a href="/account?$Launchh::HSTR">
								<i class="icon-app"></i> Profile
							</a>
						</li>
		
						<li>
							<a href="/inbox?$Launchh::HSTR">
								<i class="icon-mail"></i> Inbox 
							</a>
		
							<!--ul>
								<li>
									<a href="/inbox?$Launchh::HSTR">
										<i class="icon-mail-arrow-down"></i> Inbox
									</a>
								</li>
		
								<li>
									<a href="/inbox?$Launchh::HSTR">
										<i class="icon-mail-arrow-up"></i> Sent
									</a>
								</li>
							</ul-->
						</li>
					</ul>
				</li><!-- /.widget widget-nav -->
			</ul><!-- /.widgets -->
		</aside><!-- /.sidebar -->
EOM

   print $header;
}

sub print_footer
{

   my $footer = &Launchh::html_footer($Launchh::HFILE,$Launchh::HSTR);

    if( $pmode ne '' && !defined $session->param("pmode") ){
        $footer =~ s/privacy"/privacy\?pmode=$pmode"/is;
        $footer =~ s/terms"/terms\?pmode=$pmode"/is;
    }

    print $footer;
}
